### ISSUE TITLE
The initial sdk crashed. Procedure

### ISSUE THREAD

**Issue by HuangBiaoHb** [klaviyo/klaviyo-android-sdk#182]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-android-sdk/blob/master/.github/CONTRIBUTING.md)
- [ ] I have determined whether this bug is also reproducible in a vanilla Android project
- [ ] If possible, I've reproduced the issue using the `master` branch or latest release of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-android-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-android-sdk/pulls).

### Description

```markdown
The Klaviyo.initialize method crashes, Should I specify the kotlin version?

My version of kotlin: 1.7.20
My version of gradel: 8.3
```

### Expected behavior

```markdown
Can initialize normally
```

### Actual behavior

```markdown
crashes
 java.lang.ClassNotFoundException: Didn't find class "kotlin.enums.EnumEntriesKt" on path: DexPathList[[dex file "/data/data/com.renpho.health/code_cache/.overlay/base.apk/classes23.dex", zip file "/data/app/~~6Up3Lg5KenJ-kNQBvf88oQ==/com.renpho.health-2tg64saQQ6rPFm49PH2jdA==/base.apk"],nativeLibraryDirectories=[/data/app/~~6Up3Lg5KenJ-kNQBvf88oQ==/com.renpho.health-2tg64saQQ6rPFm49PH2jdA==/lib/arm64, /data/app/~~6Up3Lg5KenJ-kNQBvf88oQ==/com.renpho.health-2tg64saQQ6rPFm49PH2jdA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
                                                                                                    │ 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    │ 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    │ 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    │  Caused by: java.lang.NoClassD
                                                                                                    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2024-08-28 16:21:17.620 25398-25398 CrashHandler            com.renpho.health                    E   
                                                                                                    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    │ efFoundError: Failed resolution of: Lkotlin/enums/EnumEntriesKt;
                                                                                                    │ 	at com.klaviyo.core.config.Log$Level.<clinit>(Log.kt:15)
                                                                                                    │ 	at com.klaviyo.core.KLog.<clinit>(KLog.kt:60)
                                                                                                    │ 	at com.klaviyo.core.Registry$1.invoke(Registry.kt:69)
                                                                                                    │ 	at com.klaviyo.core.Registry.getLog(Registry.kt:170)
                                                                                                    │ 	at com.klaviyo.core.networking.KlaviyoNetworkMonitor.initializeNetworkListener(KlaviyoNetworkMonitor.kt:117)
                                                                                                    │ 	at com.klaviyo.core.networking.KlaviyoNetworkMonitor.onNetworkChange(KlaviyoNetworkMonitor.kt:62)
                                                                                                    │ 	at com.klaviyo.core.networking.KlaviyoNetworkMonitor.<clinit>(KlaviyoNetworkMonitor.kt:51)
                                                                                                    │ 	at com.klaviyo.core.Registry.getNetworkMonitor(Registry.kt:50)
                                                                                                    │ 	at com.klaviyo.analytics.networking.KlaviyoApiClient.startService(KlaviyoApiClient.kt:45)
                                                                                                    │ 	at com.klaviyo.analytics.Klaviyo$initialize$1.invoke(Klaviyo.kt:81)
                                                                                                    │ 	at com.klaviyo.analytics.Klaviyo$initialize$1.invoke(Klaviyo.kt:65)
```

### Steps to reproduce

```markdown
1. application -> Klaviyo.initialize("xxxxx", applicationContext)
```

### The Klaviyo Android SDK version information

2.4.0

### Device Information

Galaxy s21

### Android Studio Version

 2023.3.1 Patch 1

### Android API Level

34

**Comment by HuangBiaoHb** [comment]
![微信图片_20240828170323](https://github.com/user-attachments/assets/f1886391-a65d-434c-94c0-ca15df580d51)

**Comment by HuangBiaoHb** [comment]
It should be the kotlin version that causes the crash

**Comment by HuangBiaoHb** [comment]
Thank you. It should be that our project has developed a kotlin version, and there was a problem of too many versions reporting errors before

**Comment by HuangBiaoHb** [comment]
Thank you. It seems that our project has specified the kotlin version, and there was a problem of too many versions reporting errors

**Comment by HuangBiaoHb** [comment]
I will try to upgrade the kotlin version

**Comment by dan-peluso** [comment]
https://github.com/klaviyo/klaviyo-android-sdk/pull/183
